### ISSUE TITLE
How to do Pagination?

### ISSUE THREAD

**Issue by mchalise** [davidmetta/ru_bittrex#4]
Could you help me with Pagination:

eg: GET /deposits/closed

Max Page Size: 200

How to get more than 200 deposits?
I tried applying last and first "ID" for next query with "previousPageToken" or "nextPageToken" :  one is returning same data and other is giving "SIGNATURE ERROR".    

Thanks in advance.

**Comment by davidmetta** [comment]
@mchalise let me look into it, will get back to you soon.

**Comment by mchalise** [comment]
I got it worked out. @davidmetta The pageSize was giving that issue. So when I only passed nextPageToken. It worked. Thanks. Closing this ticket.
